version: '3.8'

services:
  coap-gateway:
    build: ./gateway
    container_name: coap-gateway
    networks:
      coap-iot-network:
      coap-client-network:
    ports:
      - "3000:3000"  # 映射 HTTP port (client -> Gateway)
      - "3001:3001"  # 映射 Span Collector port
    environment:
      - SPAN_HANDLER_HOST=host.docker.internal
      - SPAN_HANDLER_PORT=3333
      - IOT_SERVER_A_PORT=5683
      - IOT_SERVER_A_HOST=coap-iot-server-a
    extra_hosts:
      - "host.docker.internal:host-gateway"


  iot-server-a:
    build: ./coapServer
    cap_add:
      - ALL
    container_name: coap-iot-server-a
    privileged: true
    networks:
      coap-iot-network:
    environment:
      - IOT_SERVER_A_PORT=5683
      - GATEWAY_PORT=3001
      - GATEWAY_HOST=coap-gateway

  coap-http-client:
    build: ./httpClient
    container_name: coap-http-client
    networks:
      coap-client-network:
    depends_on:
      - coap-gateway
    environment:
      - GATEWAY_HOST=coap-gateway
      - GATEWAY_PORT=3000
      - SPAN_HANDLER_HOST=host.docker.internal
      - SPAN_HANDLER_PORT=3333
    extra_hosts:
      - "host.docker.internal:host-gateway"

  coap-span-handler:
    build: ./spanHandler
    container_name: coap-span-handler
    networks:
      coap-tracing-network:
    environment:
      - SPAN_HANDLER_PORT=3333
    ports:
      - "3333:3333"
    volumes:
      - coap-span-data:/app

networks:
  coap-iot-network:
    driver: bridge
  coap-client-network:
    driver: bridge
  coap-tracing-network:
    driver: bridge

volumes:
  coap-span-data:
